In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Generador de datos
def data_generator(board, boards, i):
    if i < 9:
        for value in [1, 0, -1]:  # Posibles valores
            new_board = board.copy()
            new_board[i] = value
            data_generator(new_board, boards, i + 1)
    else:
        boards.append(board)  # Solo añadimos al final de la generación
    return boards

# Inicialización del dataset
input_data = np.array(data_generator([0] * 9, [], 0))
output_data = input_data.copy()  # Sin normalización adicional porque usamos tanh

# Crear el modelo
model = Sequential([
    Dense(18, input_dim=9, activation='tanh'),  # Capa oculta
    Dense(9, activation='tanh')  # Capa de salida
])

# Compilar el modelo
model.compile(optimizer='adam', loss='mean_squared_error')

# Entrenar el modelo
model.fit(input_data, output_data, epochs=100)

2024-11-29 10:26:40.338346: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-29 10:26:54.997308: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


Epoch 1/100
616/616 [==============================] - 2s 1ms/step - loss: 0.2045
Epoch 2/100
616/616 [==============================] - 1s 1ms/step - loss: 0.0173
Epoch 3/100
616/616 [==============================] - 1s 1ms/step - loss: 0.0098
Epoch 4/100
616/616 [==============================] - 1s 2ms/step - loss: 0.0070
Epoch 5/100
616/616 [==============================] - 1s 1ms/step - loss: 0.0053
Epoch 6/100
616/616 [==============================] - 1s 1ms/step - loss: 0.0042
Epoch 7/100
616/616 [==============================] - 1s 1ms/step - loss: 0.0033
Epoch 8/100
616/616 [==============================] - 1s 2ms/step - loss: 0.0027
Epoch 9/100
616/616 [==============================] - 1s 2ms/step - loss: 0.0022
Epoch 10/100
616/616 [==============================] - 1s 2ms/step - loss: 0.0018
Epoch 11/100
616/616 [==============================] - 1s 1ms/step - loss: 0.0015
Epoch 12/100
616/616 [==============================] - 1s 1ms/step - loss: 0.0012
Epoch 13/100


In [8]:

# Hacer predicciones (deberían ser similares a las entradas)
predictions = model.predict(input_data)

# Mostrar algunas predicciones
def round_to_choices(values):
    return np.clip(np.round(values), -1, 1)

# Redondear las predicciones
rounded_predictions = np.vectorize(round_to_choices)(predictions)

# Mostrar algunas predicciones redondeadas
print(rounded_predictions[:5]) # Imprimir las primeras 5 predicciones
print(input_data[:5])


616/616 [==============================] - 1s 2ms/step
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1. -0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1. -0. -0.]]
[[ 1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  0]
 [ 1  1  1  1  1  1  1  1 -1]
 [ 1  1  1  1  1  1  1  0  1]
 [ 1  1  1  1  1  1  1  0  0]]
